version: "3"

networks:
  discordx-network:
    name: discordx-network

services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4.2.2
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G
      - SERVER_PORT=2333
      - LAVALINK_PASSWORD=${LAVALINK_PASSWORD}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    networks:
      - discordx-network
    expose:
      - 2333
    ports:
      - "2333:2333"

  app:
    depends_on:
      - lavalink
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - LAVA_HOST=lavalink
      - LAVA_PORT=2333
    networks:
      - discordx-network
    command: node build/main.js
