apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}-bot
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: bot
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: bot
    spec:
      initContainers:
        - name: wait-for-lavalink
          image: busybox:1.36
          command:
            - sh
            - -c
            - until nc -z {{ include "common.fullname" . }}-lavalink.{{ .Values.namespace }}.svc.cluster.local {{ .Values.service.lavalink.port }}; do echo waiting for lavalink; sleep 2; done;
      containers:
        - name: bot
          image: "{{ .Values.image.bot.repository }}:{{ .Values.image.bot.tag }}"
          imagePullPolicy: {{ .Values.image.bot.pullPolicy }}
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.fullname" . }}
                  key: BOT_TOKEN
            - name: LAVA_HOST
              value: {{ include "common.fullname" . }}-lavalink.{{ .Values.namespace }}.svc.cluster.local
            - name: LAVA_PORT
              value: {{ .Values.service.lavalink.port | quote }}
            - name: LAVA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.fullname" . }}
                  key: LAVALINK_PASSWORD
          {{- if .Values.persistence.bot.logs.enabled }}
          volumeMounts:
            - name: logs
              mountPath: /app/logs
          {{- end }}
          resources:
            {{- toYaml .Values.resources.bot | nindent 12 }}
      {{- if .Values.persistence.bot.logs.enabled }}
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "common.fullname" . }}-bot-logs-pvc
      {{- end }}
