apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}-lavalink
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: lavalink
spec:
  type: {{ .Values.service.lavalink.type }}
  ports:
    - port: {{ .Values.service.lavalink.port }}
      targetPort: {{ .Values.lavalink.port }}
      protocol: TCP
      name: lavalink
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: lavalink
